spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://db:5432/repo
    username: repo
    password: repo
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
